---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- *.yml
- *.rst
- *requirements.txt
- tests/**/*
- docs/**/*
- MANIFEST.in
- setup.*
- tox.ini
- LICENSE
