language: python
python: "3.4"
sudo: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - TOXENV=check,docs,doc_travis

addons:
    code_climate:
        repo_token: fa6fc1a6c242fbdf483adf9d4743e1fc032183ae0f164bcec61e222e13623ead

matrix:
  fast_finish: true
  include:
    - python: 3.3
      env: TOXENV=3.3
    - python: 3.4
      env: TOXENV=3.4
    - python: 3.5
      env: TOXENV=3.5
    # - "nightly" currently points to 3.6-dev
    - python: nightly
      env: TOXENV=3.6


before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - echo "TRAVIS_TAG=$TRAVIS_TAG"
  - echo "repo=$TRAVIS_REPO_SLUG"

install:
  - pip install -U pip setuptools
  - pip install tox travis-sphinx>=1.4.1
  - pip install codecov>=1.4.0 codeclimate-test-reporter
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - echo "$PWD"

script:
  - tox -v -e $TOXENV

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
  # - bash <(curl -s https://codecov.io/bash)
  - coverage debug data
  - codecov --token=$CODECOV_TOKEN
  - codeclimate-test-reporter --token $CODECLIMATE_REPO_TOKEN
  - ./.travis-deploy.sh
